### ISSUE TITLE
Add an image

### ISSUE THREAD

**Issue by manuchap** [Ninja-Squad/quizz#1]
Hi! Awsome app!
How can I insert an image between the question and the answers?

**Comment by jnizet** [comment]
Thanks. Incredible to see that someone found it although we haven't talked about it yet.

If I understand correctly, you would like to insert an image in the questions, between the question text and the part where the possible answers are displayed.

If so, replace the following code in the Quizz.html file:

```
<div class="well" btf-markdown="currentQuestion.text"></div>
<form class="well">
```

By

```
<div class="well" btf-markdown="currentQuestion.text"></div>
<img src="myimage.jpg" />
<form class="well">
```

Note that the same image will be displayed on all the questions though, since this is a single page app. If I didn't understand what you meant, please clarify.

**Comment by manuchap** [comment]
Thanks for answering. I actually managed like so:

Quizz.html:

``` html
            <div class="well" btf-markdown="currentQuestion.text"></div>
            <div class="well"><img class="img-responsive" ng-src="/img/{{ currentQuestion.pict }}"/ ></div>
```

example-quizz.js:

``` javascript
    questions: [
        {
            type: 'radio',
            text: 'Is it a bird, is it a plane?',
            pict: 'bird.gif',
            answers: [
                {
                    text: 'Bird',
                    correct: true
                },
                {
                    text: 'Plane',
                    correct: false
                }
            ]
        }
```

allowing one image per question.
